# How to use it?
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/engineer-blog
  engineer-blog-spring:
    environment:
      PROFILE_ACTIVE: ${PROFILE_ACTIVE:-postgres}
      POSTGRES_DDL_AUTO: update
    networks:
      - nginx-proxy-manager_default

  engineer-blog-react:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL="${REACT_APP_BACKEND_URL}"
        - REACT_APP_GITHUB_URL="${REACT_APP_GITHUB_URL}"
    networks:
     - nginx-proxy-manager_default

  engineer-blog-db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true