# How to use it?
# docker compose -f docker-compose-prod.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/engineer-blog
  engineer-blog-spring:
    build:
      context: ./engineer-blog-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: postgres
      ADMIN_NAME: admin
      ADMIN_PASSWORD: pXmJ5M9dvP
      POSTGRES_URL: jdbc:postgresql://engineer-blog-db:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DDL_AUTO: update
    depends_on:
      - engineer-blog-db
    networks:
      - nginx-proxy-manager_default

  engineer-blog-react:
    build:
      context: .
      dockerfile: ./docker/static-server/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=https://api.ydubovitsky.ru
    networks:
     - nginx-proxy-manager_default

  engineer-blog-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - engineer-blog-db:/data/postgres
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true

volumes:
  engineer-blog-db: