# How to use it?
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/engineer-blog
  engineer-blog-spring:
    networks:
      - nginx-proxy-manager_default

  engineer-blog-react:
    networks:
     - nginx-proxy-manager_default

  engineer-blog-db:
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true