# How to init submodule
# git submodule update --init --recursive
# git submodule update --remote --merge

# How to use it?
# docker compose -f docker-compose.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/engineer-blog
  engineer-blog-spring:
    build:
      context: ./engineer-blog-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: h2
      ADMIN_NAME: ${ADMIN_NAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      POSTGRES_URL: jdbc:postgresql://engineer-blog-db:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DDL_AUTO: update
    depends_on:
      - engineer-blog-db
    networks:
      - main

  engineer-blog-react:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=http://localhost:8080
        - REACT_APP_GITHUB_URL="${REACT_APP_GITHUB_URL}"
    networks:
     - main

  engineer-blog-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - engineer-blog-db:/data/postgres
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    driver: bridge

volumes:
  engineer-blog-db: